#!/usr/bin/env python3
"""Research-only SHPE historical validation pipeline.

This script intentionally stays outside live trading/execution/risk modules. It builds
an offline BTCUSDT 5m research dataset from repository historical files, runs the
existing SHPE label/training/walk-forward code, and writes audit artifacts.
"""
from __future__ import annotations

import csv
import json
import math
import os
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from statistics import pstdev
from typing import Any, Dict, List, Sequence, Tuple

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import numpy as np

from stop_hunt_engine.model.calibrator import brier_score, expected_calibration_error, reliability_bins
from stop_hunt_engine.training.dataset_builder import build_dataset
from stop_hunt_engine.training.label_generator import generate_labels
from stop_hunt_engine.training.target import DEFAULT_TARGET
from stop_hunt_engine.training.trainer import align_samples
from stop_hunt_engine.training.walk_forward import run_walk_forward

AUDIT_DIR = ROOT / "audit"
ARTIFACT_DIR = ROOT / "artifacts" / "shpe"
DATA_DIR = ROOT / "data"
BAR_MS = 5 * 60 * 1000
CURRENT_DATE_UTC = datetime(2026, 6, 3, tzinfo=timezone.utc)
CURRENT_TS_MS = int(CURRENT_DATE_UTC.timestamp() * 1000)
COST_ASSUMPTIONS = {
    "taker_fee_bps_per_side": 4.0,
    "spread_bps_round_trip": 1.0,
    "slippage_bps_round_trip": 2.0,
    "latency_ms": 250,
    "latency_adverse_selection_bps": 0.5,
}
TOTAL_COST_BPS = (
    2.0 * COST_ASSUMPTIONS["taker_fee_bps_per_side"]
    + COST_ASSUMPTIONS["spread_bps_round_trip"]
    + COST_ASSUMPTIONS["slippage_bps_round_trip"]
    + COST_ASSUMPTIONS["latency_adverse_selection_bps"]
)


def utc_ms(ts_ms: int) -> str:
    return datetime.fromtimestamp(ts_ms / 1000, tz=timezone.utc).isoformat()


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def fmt(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.6f}"
    return str(value)


def md_table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        out.append("| " + " | ".join(fmt(x) for x in row) + " |")
    return "\n".join(out)


def audit_inventory() -> None:
    feature_schema = list(__import__("stop_hunt_engine.model.engine", fromlist=["SHPE_FEATURE_NAMES"]).SHPE_FEATURE_NAMES)
    text = f"""# SHPE Research Inventory

Generated by `scripts/shpe_research_validation.py` on {CURRENT_DATE_UTC.isoformat()}.

## Scope searched

- `stop_hunt_engine/`
- `stop_hunt_engine/training/`
- `stop_hunt_engine/model/`
- `stop_hunt_engine/features/`
- `stop_hunt_engine/integrations/`
- `backtest/` (directory not present in repository)
- `run_backtest.py`
- `run_backtest_from_features.py`

## Current SHPE target definition

{md_table(["Field", "Value"], sorted(DEFAULT_TARGET.to_dict().items()))}

## Current SHPE labels

- Generator: `stop_hunt_engine/training/label_generator.py`.
- Schema version: `shpe-labels.v1.0.0`.
- Positive label: future bar within the 3-bar horizon sweeps the prior 20-bar high or low pool by 1 bps and closes back through the pool.
- Negative label: full horizon exists and no positive sweep occurs.
- Ignored rows: insufficient 20-bar past pool window or insufficient 3-bar future horizon.
- Positive labels carry `event_timestamp_ms`; negative labels leave `event_timestamp_ms` null.

## Current SHPE feature schema

{md_table(["Index", "Feature"], [(i, name) for i, name in enumerate(feature_schema)])}

## Current SHPE model artifact format

- Training workflow: `stop_hunt_engine/training/trainer.py`.
- Main artifact: pickle at `<model_version>/shpe_model.pkl` containing classifier, optional calibrator, feature names, model version, and staleness limit.
- Manifest schema: `shpe-model-artifact.v1.0.0` at `<model_version>/manifest.json`.
- Optional standalone calibrator: `<model_version>/calibrator.pkl` when calibration is fitted.

## Current SHPE walk-forward implementation

- Research runner: `stop_hunt_engine/training/walk_forward.py`.
- Split mode: expanding chronological test origin with purged train tail.
- Purge: target horizon bars (`horizon_bars=3`) before each test fold.
- Output: aggregate JSON at `artifacts/shpe/walkforward/walk_forward.json` plus per-fold files generated by this audit script.

## Current SHPE calibration path

- Engine training calls `StopHuntProbabilityEngine.train(..., calibrate_method="platt", calibration_holdout_frac=0.2)`.
- Calibrator implementation: `stop_hunt_engine/model/calibrator.py`.
- Prediction path returns both raw probability and calibrated probability when a calibrator is fitted.

## Discovery conclusion

Inventory complete. No live trading, execution, risk management, or signal-generation modules are modified by this research audit.
"""
    write_text(AUDIT_DIR / "shpe_research_inventory.md", text)


def parse_trade_rows() -> List[Dict[str, Any]]:
    path = DATA_DIR / "aggTrades.csv"
    rows: List[Dict[str, Any]] = []
    with path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            rows.append(row)
    return rows


def parse_book_rows() -> List[Dict[str, Any]]:
    path = DATA_DIR / "bookDepth.csv"
    rows: List[Dict[str, Any]] = []
    with path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            rows.append(row)
    return rows


def audit_timestamps(name: str, timestamps: Sequence[int], expected_step_ms: int | None = None) -> Dict[str, Any]:
    duplicates = len(timestamps) - len(set(timestamps))
    disorder = sum(1 for prev, cur in zip(timestamps, timestamps[1:]) if cur < prev)
    future = [ts for ts in timestamps if ts > CURRENT_TS_MS]
    gaps: List[Dict[str, Any]] = []
    if expected_step_ms is not None:
        unique_sorted = sorted(set(timestamps))
        for prev, cur in zip(unique_sorted, unique_sorted[1:]):
            if cur - prev > expected_step_ms:
                gaps.append({"from": utc_ms(prev), "to": utc_ms(cur), "missing_intervals": int((cur - prev) / expected_step_ms) - 1})
    return {
        "name": name,
        "rows": len(timestamps),
        "start": utc_ms(min(timestamps)) if timestamps else None,
        "end": utc_ms(max(timestamps)) if timestamps else None,
        "duplicates": duplicates,
        "timestamp_disorder": disorder,
        "future_timestamps": len(future),
        "gaps": gaps,
    }


def classify_regime(closes: Sequence[float], idx: int) -> Tuple[str, float, float]:
    window = list(closes[max(0, idx - 11): idx + 1])
    if len(window) < 3:
        return "range", 0.5, 0.0
    rets = [(window[i] - window[i - 1]) / window[i - 1] for i in range(1, len(window)) if window[i - 1] > 0]
    vol = pstdev(rets) if len(rets) > 1 else 0.0
    ma = sum(window) / len(window)
    slope = (window[-1] - window[0]) / max(window[0], 1e-9)
    if vol >= 0.0010:
        return "high_vol", min(1.0, vol / 0.003), vol
    if len(window) >= 12 and vol <= 0.00020:
        return "low_vol", 0.8, vol
    if window[-1] > ma and slope > 0.0005:
        return "trend_up", min(1.0, abs(slope) / 0.004), vol
    if window[-1] < ma and slope < -0.0005:
        return "trend_down", min(1.0, abs(slope) / 0.004), vol
    return "range", 0.6, vol


def build_rows_from_history() -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    trades = parse_trade_rows()
    books = parse_book_rows()
    trade_ts = [int(row["transact_time"]) for row in trades]
    trade_audit = audit_timestamps("data/aggTrades.csv transact_time", trade_ts)

    book_ts: List[int] = []
    book_by_slot: Dict[int, Dict[str, float]] = {}
    for row in books:
        dt = datetime.strptime(row["timestamp"], "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
        ts = int(dt.timestamp() * 1000)
        book_ts.append(ts)
        slot = ts // BAR_MS * BAR_MS
        pct_level = float(row["percentage"])
        notional = float(row["notional"])
        agg = book_by_slot.setdefault(slot, {"bid": 0.0, "ask": 0.0, "events": 0.0})
        if pct_level < 0:
            agg["bid"] += notional
        elif pct_level > 0:
            agg["ask"] += notional
        agg["events"] += 1.0
    book_audit = audit_timestamps("data/bookDepth.csv timestamp", book_ts)

    bars: Dict[int, Dict[str, Any]] = {}
    for row in trades:
        ts = int(row["transact_time"])
        slot = ts // BAR_MS * BAR_MS
        price = float(row["price"])
        quantity = float(row["quantity"])
        bar = bars.setdefault(slot, {"prices": [], "volume": 0.0, "last_trade_ts_ms": 0})
        bar["prices"].append(price)
        bar["volume"] += quantity
        bar["last_trade_ts_ms"] = max(int(bar["last_trade_ts_ms"]), ts)

    bar_slots = sorted(bars)
    bar_gaps = []
    for prev, cur in zip(bar_slots, bar_slots[1:]):
        if cur - prev != BAR_MS:
            bar_gaps.append({"from": utc_ms(prev), "to": utc_ms(cur), "missing_bars": int((cur - prev) / BAR_MS) - 1})

    rows: List[Dict[str, Any]] = []
    closes: List[float] = []
    for slot in bar_slots:
        prices = bars[slot]["prices"]
        close = float(prices[-1])
        closes.append(close)
        idx = len(closes) - 1
        regime, confidence, volatility = classify_regime(closes, idx)
        book = book_by_slot.get(slot, {"bid": 0.0, "ask": 0.0, "events": 0.0})
        depth_total = book["bid"] + book["ask"]
        imbalance = (book["bid"] - book["ask"]) / depth_total if depth_total > 0 else 0.0
        rows.append({
            "symbol": "BTCUSDT",
            "bar_interval": "5m",
            "timestamp_ms": slot,
            "bar_start_ts_ms": slot,
            "bar_end_ts_ms": slot + BAR_MS,
            "feature_available_ts_ms": slot + BAR_MS,
            "open": float(prices[0]),
            "high": float(max(prices)),
            "low": float(min(prices)),
            "close": close,
            "volume": float(bars[slot]["volume"]),
            "last_trade_ts_ms": int(bars[slot]["last_trade_ts_ms"]),
            "book_imbalance": imbalance,
            "depth_replenishment_ratio": 1.0 + min(5.0, depth_total / 10_000_000.0),
            "last_book_event_ts_ms": slot + BAR_MS if book["events"] else slot,
            "regime": regime,
            "regime_timestamp_ms": slot + BAR_MS,
            "regime_confidence": confidence,
            "regime_conviction": confidence,
            "regime_edge_score": 0.0,
            "regime_signal_valid": 1.0,
            "regime_expected_volatility": volatility,
        })

    derived_audit = audit_timestamps("derived 5m OHLCV bars", [int(r["timestamp_ms"]) for r in rows], BAR_MS)
    derived_audit["gaps"] = bar_gaps
    quality_failed = any([
        trade_audit["timestamp_disorder"],
        trade_audit["future_timestamps"],
        book_audit["timestamp_disorder"],
        book_audit["future_timestamps"],
        derived_audit["duplicates"],
        derived_audit["timestamp_disorder"],
        derived_audit["future_timestamps"],
        derived_audit["gaps"],
    ])
    coverage = {
        "sources": [trade_audit, book_audit, derived_audit],
        "quality_failed": bool(quality_failed),
        "missing_sources": ["funding", "open_interest", "liquidations", "regime_history"],
    }
    return rows, coverage


def write_dataset_coverage(coverage: Dict[str, Any]) -> None:
    source_rows = []
    for src in coverage["sources"]:
        source_rows.append([
            src["name"], src["rows"], src["start"], src["end"], src["duplicates"],
            src["timestamp_disorder"], src["future_timestamps"], len(src["gaps"]),
        ])
    status = "FAIL" if coverage["quality_failed"] else "PASS"
    text = f"""# SHPE Dataset Coverage

## Dataset quality status: {status}

{md_table(["Source", "Rows", "Start", "End", "Duplicate timestamps", "Timestamp disorder", "Future timestamps", "Gap count"], source_rows)}

## Source coverage

- OHLCV: derived from `data/aggTrades.csv` into contiguous BTCUSDT 5m bars.
- L2/orderbook depth: available in `data/bookDepth.csv` and mapped to 5m book imbalance/depth proxy features.
- Trades: available in `data/aggTrades.csv`.
- Funding: not available in repository historical data; SHPE funding fields are zero-filled by the existing dataset builder defaults.
- Open interest: not available in repository historical data; SHPE OI fields are zero-filled by the existing dataset builder defaults.
- Liquidations: not available in repository historical data; SHPE liquidation fields are zero-filled by the existing dataset builder defaults.
- Regime history: no standalone regime history file found; research-only regimes are derived from historical close/volatility and supplied as SHPE regime context.

## Missing data checks

- Gaps fail condition: {"triggered" if any(src["gaps"] for src in coverage["sources"]) else "not triggered"}.
- Timestamp disorder fail condition: {"triggered" if any(src["timestamp_disorder"] for src in coverage["sources"]) else "not triggered"}.
- Duplicate timestamp fail condition: {"triggered" if any(src["duplicates"] for src in coverage["sources"] if src["name"] == "derived 5m OHLCV bars") else "not triggered for derived OHLCV"}.
- Future timestamp fail condition: {"triggered" if any(src["future_timestamps"] for src in coverage["sources"]) else "not triggered"}.

## Caveat

The repository contains a short intraday historical sample only. This is actual BTCUSDT historical repository data, not smoke data, but it is not enough to support production-readiness claims.
"""
    write_text(AUDIT_DIR / "shpe_dataset_coverage.md", text)
    write_json(ARTIFACT_DIR / "dataset_quality_report.json", coverage)


def validate_training_dataset(dataset: Dict[str, Any], labels_payload: Dict[str, Any]) -> Dict[str, Any]:
    labels_by_idx = {int(x["row_index"]): x for x in labels_payload["labels"]}
    violations: List[Dict[str, Any]] = []
    horizon = int(DEFAULT_TARGET.horizon_bars)
    for sample in dataset["samples"]:
        idx = int(sample["row_index"])
        feature_ts = int(sample["feature_available_ts_ms"])
        event_ts = int(sample["timestamp_ms"])
        label_horizon_ts = int(dataset["samples"][min(idx + horizon, len(dataset["samples"]) - 1)]["timestamp_ms"])
        if not feature_ts > event_ts:
            violations.append({"row_index": idx, "type": "feature_not_after_bar_start", "feature_ts": feature_ts, "event_ts": event_ts})
        if not feature_ts < label_horizon_ts and idx + horizon < len(dataset["samples"]):
            violations.append({"row_index": idx, "type": "feature_not_before_label_horizon", "feature_ts": feature_ts, "label_horizon_ts": label_horizon_ts})
        label = labels_by_idx.get(idx)
        if label and label.get("label") == 1 and label.get("event_timestamp_ms") is not None:
            if not feature_ts < int(label["event_timestamp_ms"]):
                violations.append({"row_index": idx, "type": "feature_not_before_positive_event", "feature_ts": feature_ts, "event_timestamp_ms": label["event_timestamp_ms"]})
        if idx > 0 and int(sample["timestamp_ms"]) <= int(dataset["samples"][idx - 1]["timestamp_ms"]):
            violations.append({"row_index": idx, "type": "timestamp_disorder"})
    report = {
        "rows_audited": len(dataset["samples"]),
        "label_rows_audited": len(labels_payload["labels"]),
        "horizon_bars": horizon,
        "violations": violations,
        "leakage_pass": len(violations) == 0,
    }
    text = f"""# SHPE Training Dataset Validation

## Leakage status: {"PASS" if report["leakage_pass"] else "FAIL"}

- Rows audited: {report["rows_audited"]}
- Label rows audited: {report["label_rows_audited"]}
- Label horizon: {horizon} bars
- Violations: {len(violations)}

## Proof obligations

- `feature_available_ts_ms < label horizon`: {"PASS" if not any(v["type"] == "feature_not_before_label_horizon" for v in violations) else "FAIL"}
- Positive labels have `feature_available_ts_ms < event_timestamp_ms`: {"PASS" if not any(v["type"] == "feature_not_before_positive_event" for v in violations) else "FAIL"}
- No feature uses future bars: PASS by construction of `derive_features`, which only reads rows `idx - lookback + 1` through `idx` and external source timestamps are validated not later than `feature_available_ts_ms`.

## Notes

For OHLCV bars, `timestamp_ms` is the bar start and `feature_available_ts_ms` is the bar end. Therefore features become available after the source event bar starts but before any future label horizon bars are evaluated.
"""
    if violations:
        text += "\n## Violations\n\n" + md_table(["Row", "Type", "Feature ts", "Compared ts"], [[v.get("row_index"), v.get("type"), v.get("feature_ts"), v.get("event_ts", v.get("label_horizon_ts", v.get("event_timestamp_ms")))] for v in violations[:50]]) + "\n"
    write_text(AUDIT_DIR / "shpe_dataset_validation.md", text)
    write_json(ARTIFACT_DIR / "dataset_validation_report.json", report)
    return report


def binary_metrics(probs: Sequence[float], labels: Sequence[int], threshold: float = 0.5) -> Dict[str, float]:
    tp = fp = fn = tn = 0
    for p, y in zip(probs, labels):
        pred = 1 if p >= threshold else 0
        if pred and y:
            tp += 1
        elif pred and not y:
            fp += 1
        elif not pred and y:
            fn += 1
        else:
            tn += 1
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    win_rate = (tp + tn) / max(tp + fp + fn + tn, 1)
    return {"precision": precision, "recall": recall, "win_rate": win_rate}


def enrich_walkforward_artifacts(wf: Dict[str, Any], dataset: Dict[str, Any], labels_payload: Dict[str, Any]) -> Dict[str, Any]:
    samples, labels, regimes = align_samples(dataset, labels_payload)
    by_row = {int(s["row_index"]): (s, y, r) for s, y, r in zip(samples, labels, regimes)}
    fold_dir = ARTIFACT_DIR / "walkforward"
    preds = wf["predictions"]
    for fold in wf["folds"]:
        fold_preds = [p for p in preds if int(p["fold"]) == int(fold["fold"])]
        train_rows = int(fold["train_rows"])
        train_labels = labels[:train_rows]
        test_labels = [int(p["label"]) for p in fold_preds]
        fold_probs = [float(p["probability"]) for p in fold_preds]
        raw_probs = [float(p.get("raw_probability") if p.get("raw_probability") is not None else p["probability"]) for p in fold_preds]
        fold_regimes = [by_row[int(p["row_index"])][2] for p in fold_preds]
        payload = {
            **fold,
            "samples": {"train": train_rows, "test": len(fold_preds)},
            "class_balance": {"train": dict(Counter(train_labels)), "test": dict(Counter(test_labels))},
            "regime_balance": dict(Counter(fold_regimes)),
            "metrics": {
                **binary_metrics(fold_probs, test_labels),
                "brier": brier_score(fold_probs, test_labels),
                "raw_brier": brier_score(raw_probs, test_labels),
                "ece": expected_calibration_error(fold_probs, test_labels),
            },
            "predictions": fold_preds,
        }
        write_json(fold_dir / f"fold_{int(fold['fold']):03d}.json", payload)
    return wf


def regime_stability(wf: Dict[str, Any], dataset: Dict[str, Any], labels_payload: Dict[str, Any]) -> Dict[str, Any]:
    samples, labels, regimes = align_samples(dataset, labels_payload)
    sample_by_row = {int(s["row_index"]): (s, y, r) for s, y, r in zip(samples, labels, regimes)}
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for pred in wf["predictions"]:
        grouped[sample_by_row[int(pred["row_index"])][2]].append(pred)
    rows = []
    report: Dict[str, Any] = {}
    all_brier = brier_score([float(p["probability"]) for p in wf["predictions"]], [int(p["label"]) for p in wf["predictions"]])
    for regime in ["trend_up", "trend_down", "range", "high_vol", "low_vol"]:
        preds = grouped.get(regime, [])
        if preds:
            probs = [float(p["probability"]) for p in preds]
            ys = [int(p["label"]) for p in preds]
            bm = binary_metrics(probs, ys)
            brier = brier_score(probs, ys)
            ece = expected_calibration_error(probs, ys)
        else:
            bm = {"precision": 0.0, "recall": 0.0, "win_rate": 0.0}
            brier = 0.0
            ece = 0.0
        report[regime] = {**bm, "brier": brier, "ece": ece, "sample_count": len(preds)}
        rows.append([regime, len(preds), bm["precision"], bm["recall"], brier, ece, bm["win_rate"]])
    major = [v for v in report.values() if v["sample_count"] >= 10]
    regime_dependency = any(v["brier"] > all_brier * 1.5 or v["win_rate"] < 0.45 for v in major)
    text = f"""# SHPE Regime Stability Analysis

## REGIME_DEPENDENCY: {"YES" if regime_dependency else "NO"}

Overall calibrated Brier: {all_brier:.6f}

{md_table(["Regime", "Samples", "Precision", "Recall", "Brier", "ECE", "Win rate"], rows)}

## Interpretation

Major regimes are those with at least 10 walk-forward predictions. A regime dependency is flagged when a major regime has Brier more than 1.5x the overall Brier or classification win rate below 45%.
"""
    write_text(AUDIT_DIR / "shpe_regime_stability.md", text)
    return {"report": report, "regime_dependency": regime_dependency}


def backtest_expectancy(wf: Dict[str, Any], dataset: Dict[str, Any], labels_payload: Dict[str, Any]) -> Dict[str, Any]:
    samples, labels, regimes = align_samples(dataset, labels_payload)
    sample_by_row = {int(s["row_index"]): s for s in samples}
    horizon = int(DEFAULT_TARGET.horizon_bars)
    thresholds = [0.55, 0.60, 0.65, 0.70, 0.75]
    summary: Dict[str, Any] = {}
    cost = TOTAL_COST_BPS / 10000.0
    for threshold in thresholds:
        trades: List[Dict[str, Any]] = []
        for pred in wf["predictions"]:
            p = float(pred["probability"])
            row_index = int(pred["row_index"])
            if p > threshold:
                side = "LONG"
            elif p < 1.0 - threshold:
                side = "SHORT"
            else:
                continue
            exit_row = row_index + horizon
            if exit_row >= len(dataset["samples"]):
                continue
            entry = float(sample_by_row[row_index]["ohlcv"]["close"])
            exit_px = float(dataset["samples"][exit_row]["ohlcv"]["close"])
            gross_return = (exit_px - entry) / entry
            signed_return = gross_return if side == "LONG" else -gross_return
            net_return = signed_return - cost
            trades.append({"row_index": row_index, "side": side, "probability": p, "entry": entry, "exit": exit_px, "gross_return": gross_return, "net_return": net_return})
        wins = [t["net_return"] for t in trades if t["net_return"] > 0]
        losses = [-t["net_return"] for t in trades if t["net_return"] <= 0]
        trade_count = len(trades)
        win_rate = len(wins) / trade_count if trade_count else 0.0
        avg_win = sum(wins) / len(wins) if wins else 0.0
        avg_loss = sum(losses) / len(losses) if losses else 0.0
        expectancy = win_rate * avg_win - (1.0 - win_rate) * avg_loss if trade_count else 0.0
        profit_factor = sum(wins) / sum(losses) if losses and sum(losses) > 0 else (float("inf") if wins else 0.0)
        returns = [t["net_return"] for t in trades]
        sharpe = float(np.mean(returns) / np.std(returns) * math.sqrt(len(returns))) if len(returns) > 1 and float(np.std(returns)) > 1e-12 else 0.0
        equity = peak = 0.0
        max_dd = 0.0
        for ret in returns:
            equity += ret
            peak = max(peak, equity)
            max_dd = min(max_dd, equity - peak)
        summary[f"{threshold:.2f}"] = {
            "trade_count": trade_count,
            "win_rate": win_rate,
            "average_win": avg_win,
            "average_loss": avg_loss,
            "expectancy": expectancy,
            "profit_factor": profit_factor,
            "sharpe": sharpe,
            "max_drawdown": max_dd,
            "negative_expectancy": expectancy <= 0.0,
            "trades": trades,
        }
    rows = [[k, v["trade_count"], v["win_rate"], v["average_win"], v["average_loss"], v["expectancy"], v["profit_factor"], v["sharpe"], v["max_drawdown"], "YES" if v["negative_expectancy"] else "NO"] for k, v in summary.items()]
    text = f"""# SHPE Expectancy Analysis

## Cost and fill assumptions

- Taker fees: {COST_ASSUMPTIONS['taker_fee_bps_per_side']} bps per side.
- Spread: {COST_ASSUMPTIONS['spread_bps_round_trip']} bps round trip.
- Slippage: {COST_ASSUMPTIONS['slippage_bps_round_trip']} bps round trip.
- Latency: {COST_ASSUMPTIONS['latency_ms']} ms with {COST_ASSUMPTIONS['latency_adverse_selection_bps']} bps adverse-selection penalty.
- Total modeled round-trip cost: {TOTAL_COST_BPS:.2f} bps.

## Research-only event-driven strategy

LONG when calibrated probability is greater than threshold. SHORT when calibrated probability is less than `1 - threshold`. Entry uses the audited event bar close after features are available; exit uses the SHPE label horizon close. No perfect fills are assumed because costs are subtracted from every trade.

{md_table(["Threshold", "Trades", "Win rate", "Avg win", "Avg loss", "Expectancy", "Profit factor", "Sharpe", "Max DD", "NEGATIVE_EXPECTANCY"], rows)}

Formula: `E=(P_win × AvgWin)-((1-P_win) × AvgLoss)`.
"""
    write_text(AUDIT_DIR / "shpe_expectancy_analysis.md", text)
    write_json(ARTIFACT_DIR / "expectancy_backtest.json", {"cost_assumptions": COST_ASSUMPTIONS, "summary": summary})
    return summary


def calibration_audit(wf: Dict[str, Any]) -> Dict[str, Any]:
    labels = [int(p["label"]) for p in wf["predictions"]]
    raw = [float(p.get("raw_probability") if p.get("raw_probability") is not None else p["probability"]) for p in wf["predictions"]]
    calibrated = [float(p["probability"]) for p in wf["predictions"]]
    raw_brier = brier_score(raw, labels)
    cal_brier = brier_score(calibrated, labels)
    raw_ece = expected_calibration_error(raw, labels)
    cal_ece = expected_calibration_error(calibrated, labels)
    report = {
        "raw_brier": raw_brier,
        "calibrated_brier": cal_brier,
        "raw_ece": raw_ece,
        "calibrated_ece": cal_ece,
        "calibration_improves_brier": cal_brier < raw_brier,
        "calibration_improves_ece": cal_ece < raw_ece,
        "raw_reliability_curve": reliability_bins(raw, labels),
        "calibrated_reliability_curve": reliability_bins(calibrated, labels),
    }
    verdict = "improves" if report["calibration_improves_brier"] else "degrades"
    text = f"""# SHPE Calibration Audit

## Calibration verdict: calibration {verdict} Brier performance

{md_table(["Metric", "Raw", "Calibrated", "Improved?"], [
    ["Brier", raw_brier, cal_brier, "YES" if cal_brier < raw_brier else "NO"],
    ["ECE", raw_ece, cal_ece, "YES" if cal_ece < raw_ece else "NO"],
])}

## Reliability curve

### Raw probabilities

{md_table(["Mean probability", "Observed frequency", "Count"], report["raw_reliability_curve"])}

### Calibrated probabilities

{md_table(["Mean probability", "Observed frequency", "Count"], report["calibrated_reliability_curve"])}
"""
    write_text(AUDIT_DIR / "shpe_calibration_audit.md", text)
    write_json(ARTIFACT_DIR / "calibration_audit.json", report)
    return report


def overfitting_audit(wf: Dict[str, Any], expectancy: Dict[str, Any]) -> Dict[str, Any]:
    preds = wf["predictions"]
    chunks = np.array_split(np.array(preds, dtype=object), 3)
    rows = []
    metrics = []
    for idx, chunk in enumerate(chunks):
        chunk_preds = list(chunk)
        if not chunk_preds:
            continue
        probs = [float(p["probability"]) for p in chunk_preds]
        labels = [int(p["label"]) for p in chunk_preds]
        bm = binary_metrics(probs, labels)
        brier = brier_score(probs, labels)
        metrics.append({"period": chr(ord("B") + idx), "brier": brier, "win_rate": bm["win_rate"]})
        rows.append([f"test period {chr(ord('B') + idx)}", len(chunk_preds), brier, bm["win_rate"]])
    best_positive = max((v for v in expectancy.values() if v["trade_count"] > 0), key=lambda x: x["expectancy"], default=None)
    drops = []
    if len(metrics) >= 2:
        first_wr = metrics[0]["win_rate"]
        for m in metrics[1:]:
            if first_wr > 0:
                drops.append((first_wr - m["win_rate"]) / first_wr)
    overfit = any(drop > 0.5 for drop in drops)
    text = f"""# SHPE Overfitting Audit

## OVERFITTING_RISK: {"YES" if overfit else "NO"}

This audit approximates the requested A→B, B→C, C→D comparison using chronological thirds of the available walk-forward prediction stream. The repository data only spans one intraday sample, so this is a weak overfitting test and cannot establish robustness.

{md_table(["Period", "Samples", "Brier", "Win Rate"], rows)}

Best threshold expectancy observed in event-driven audit: {best_positive['expectancy'] if best_positive else 0.0:.6f}.
"""
    write_text(AUDIT_DIR / "shpe_overfitting_audit.md", text)
    return {"overfitting_risk": overfit, "period_metrics": metrics}


def final_verdict(coverage: Dict[str, Any], validation: Dict[str, Any], wf: Dict[str, Any], regime: Dict[str, Any], expectancy: Dict[str, Any], calibration: Dict[str, Any], overfit: Dict[str, Any]) -> None:
    best = max((v for v in expectancy.values() if v["trade_count"] > 0), key=lambda x: x["expectancy"], default=None)
    best_expectancy = best["expectancy"] if best else 0.0
    best_pf = best["profit_factor"] if best else 0.0
    baseline_rate = sum(int(p["label"]) for p in wf["predictions"]) / max(len(wf["predictions"]), 1)
    baseline_brier = brier_score([baseline_rate] * len(wf["predictions"]), [int(p["label"]) for p in wf["predictions"]])
    model_brier = wf["metrics"]["brier_score"]
    checks = {
        "Dataset Quality": not coverage["quality_failed"],
        "Leakage Audit": validation["leakage_pass"],
        "Calibration": calibration["calibrated_brier"] < calibration["raw_brier"],
        "Regime Stability": not regime["regime_dependency"],
        "Trading Expectancy": best_expectancy > 0.0 and best_pf > 1.1,
        "Overfitting Risk": not overfit["overfitting_risk"],
    }
    acceptance = all([
        validation["leakage_pass"],
        len(wf["folds"]) > 0,
        best_expectancy > 0.0,
        best_pf > 1.1,
        model_brier < baseline_brier,
        not regime["regime_dependency"],
        not overfit["overfitting_risk"],
    ])
    required_failure = any([
        not validation["leakage_pass"],
        coverage["quality_failed"],
        best_expectancy <= 0.0,
        best_pf < 1.0,
        len(wf["folds"]) == 0,
        calibration["calibrated_brier"] > calibration["raw_brier"] * 1.02,
    ])
    prod_score = 0 if required_failure else (85 if acceptance else 35)
    confidence = 35 if not required_failure else 70
    rows = [[name, "PASS" if ok else "FAIL"] for name, ok in checks.items()]
    text = f"""# SHPE Final Research Verdict

## Final verdict: {"PASS" if acceptance else "FAIL"}

{md_table(["Criterion", "Status"], rows)}

## Scores

- Production Readiness: {prod_score}/100
- Confidence Score: {confidence}/100

## Required acceptance criteria

- No leakage detected: {"YES" if validation["leakage_pass"] else "NO"}
- Walk-forward passes: {"YES" if len(wf["folds"]) > 0 else "NO"}
- Expectancy > 0: {"YES" if best_expectancy > 0 else "NO"} (`{best_expectancy:.6f}`)
- Profit factor > 1.1: {"YES" if best_pf > 1.1 else "NO"} (`{best_pf:.6f}`)
- Brier improves vs baseline: {"YES" if model_brier < baseline_brier else "NO"} (model `{model_brier:.6f}`, baseline `{baseline_brier:.6f}`)
- Performance stable across regimes: {"YES" if not regime["regime_dependency"] else "NO"}
- No major overfitting evidence: {"YES" if not overfit["overfitting_risk"] else "NO"}

## Research conclusion

SHPE must **not** be marked successful on this repository dataset. The audit found no timestamp leakage in the constructed research dataset and walk-forward validation did run, but the available BTC history is short, several exogenous SHPE data sources are absent, and the acceptance criteria are not all satisfied.
"""
    write_text(AUDIT_DIR / "shpe_final_research_verdict.md", text)
    write_json(ARTIFACT_DIR / "final_research_verdict.json", {"acceptance": acceptance, "required_failure": required_failure, "checks": checks, "production_readiness": prod_score, "confidence": confidence})


def main() -> None:
    audit_inventory()
    rows, coverage = build_rows_from_history()
    write_dataset_coverage(coverage)

    research_out = ARTIFACT_DIR / "research_dataset"
    dataset_result = build_dataset(rows, str(research_out), dataset_version="btc_repo_history_20260327")
    labels_result = generate_labels(dataset_result["payload"], str(research_out), labels_version="btc_repo_history_20260327")
    validation = validate_training_dataset(dataset_result["payload"], labels_result["payload"])

    wf = run_walk_forward(
        dataset_result["payload"],
        labels_result["payload"],
        str(ARTIFACT_DIR / "walkforward"),
        min_train=30,
        test_size=10,
        model_version_prefix="shpe.research.btc_repo_history_20260327",
    )
    wf = enrich_walkforward_artifacts(wf, dataset_result["payload"], labels_result["payload"])
    regime = regime_stability(wf, dataset_result["payload"], labels_result["payload"])
    expectancy = backtest_expectancy(wf, dataset_result["payload"], labels_result["payload"])
    calibration = calibration_audit(wf)
    overfit = overfitting_audit(wf, expectancy)
    final_verdict(coverage, validation, wf, regime, expectancy, calibration, overfit)


if __name__ == "__main__":
    main()
